version: "3"

services:
  server:
    build: 
      context: AppqAPI
      dockerfile: dockerfile
    command: "npx nodemon"
    environment:
      MONGO_URL: "mongodb://db:27017/appqdb"
      JWT_SECRET: "somesecrettoken"
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./AppqAPI:/usr/src
      - ./AppqAPI/node_modules:/usr/src/node_modules
    networks:
      - backend
  
  scrapper:
    build: 
      context: AppQScrapper
      dockerfile: dockerfile
    command: "npm start"
    environment:
      MONGO_URL: "mongodb://db:27017/appqdb"
      JWT_SECRET: "somesecrettoken"
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./AppQScrapper:/usr/src
      - ./AppQScrapper/node_modules:/usr/src/node_modules
    networks:
      - backend

  db:
    image: mongo
    volumes:
      - mongodata:/data/db
    networks:
      - backend
    ports:
      - 27017:27017

volumes:
  mongodata:

networks:
  backend:
